# Generated by Django 4.1.7 on 2023-05-29 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_thumbnail_user_profile_piq_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='administrator',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='airlinecompany',
            old_name='country_id',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='airlinecompany',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='airline_company_id',
            new_name='airline_company',
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='destination_country_id',
            new_name='destination_country',
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='origin_country_id',
            new_name='origin_country',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='flight_id',
            new_name='flight',
        ),
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together={('flight', 'customer')},
        ),
    ]
