# Generated by Django 4.1.7 on 2023-05-29 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_user_id_administrator_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='airline_company',
            new_name='airline_company_id',
        ),
    ]
