# Generated by Django 4.1.7 on 2023-05-29 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_airline_company_flight_airline_company_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='airline_company_id',
            new_name='airline_company',
        ),
    ]
