# Generated by Django 4.1.7 on 2023-05-30 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rename_airline_company_id_flight_airline_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='credit_card_no',
            field=models.CharField(max_length=19, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_no',
            field=models.CharField(max_length=13, unique=True),
        ),
    ]
