# Generated by Django 4.1.7 on 2023-05-31 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('base', '0006_alter_customer_credit_card_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrole',
            name='group',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
    ]
