# Generated by Django 4.1.7 on 2023-05-31 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_userrole_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='profile_piq',
            new_name='profile_pic',
        ),
    ]
