# Generated by Django 4.1.7 on 2023-08-27 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_country_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, default='https://api.dicebear.com/6.x/bottts-neutral/svg', null=True, upload_to='users/'),
        ),
    ]
